global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'loan-service'
    static_configs:
      - targets: ['host.docker.internal:5001']
    metrics_path: '/metrics'

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['host.docker.internal:5002']
    metrics_path: '/metrics'